### ISSUE TITLE
Prettier YAML lists

### ISSUE THREAD

**Issue by MartinHammarstedt** [spraakbanken/mink-frontend#180]
Currently, lists are not indented, making the hierarchy harder to interpret:

```yaml
korp:
  context:
  - 1 sentence
  - 5 sentence
```

In my opinion this would be easier to read:

```yaml
korp:
  context:
    - 1 sentence
    - 5 sentence
```
